ZktSn0w:
    Inertia:
      assetVersioning:
        strategy:
          class: \ZktSn0w\Inertia\Domain\AssetVersion\SettingVersionStrategy
          options:
            value: 'foobar'
        # strategy:
        #   class: \Vendor.Site\Domain\AssetVersion\MyStrategy
        #   options:
        #     ...
      fusion:
        fusionPathPatterns:
          - 'resource://Neos.Fusion/Private/Fusion'
          - 'resource://Neos.Neos/Private/Fusion'
          - 'resource://Neos.Fusion.Form/Private/Fusion'
          - 'resource://ZktSn0w.Inertia/Private/Fusion'
