ZktSn0w:
    Inertia:
      assetVersioning:
        strategy:
          class: \ZktSn0w\Inertia\Domain\AssetVersion\SettingStrategy
          options:
            value: '1.0.0'
        # strategy:
        #   class: \Vendor.Site\Domain\AssetVersion\MyStrategy
        #   options:
